/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        canvas: "#F8FAFC",
        ink: "#0F172A",
        paper: "#FFFFFF",
        cardalt: "#FFFFFF",
        rule: "#E2E8F0",
        linesoft: "#F1F5F9",
        muted: "#64748B",
        faint: "#94A3B8",
        accent: "#4F46E5",
        accenthover: "#4338CA",
        accenttint: "#EEF2FF",
        accentsoft: "#E0E7FF",
        success: "#10B981",
        successtint: "#ECFDF5",
        warning: "#F59E0B",
        warningtint: "#FFFBEB",
        danger: "#EF4444",
        dangertint: "#FEF2F2",
        ledgergreen: "#10B981",
        amber: "#F59E0B",
        ledgerred: "#EF4444",
        rust: "#4F46E5",
        rustdark: "#4338CA",
        rustlight: "#EEF2FF",
      },
      fontFamily: {
        mono: [
          "IBM Plex Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Consolas",
          "monospace",
        ],
        display: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "sans-serif",
        ],
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "sans-serif",
        ],
      },
      boxShadow: {
        soft: "0 1px 3px rgba(15, 23, 42, 0.04), 0 8px 24px -4px rgba(15, 23, 42, 0.08)",
        card: "0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 16px -2px rgba(15, 23, 42, 0.06)",
        elevated: "0 4px 6px -1px rgba(15, 23, 42, 0.05), 0 20px 40px -8px rgba(15, 23, 42, 0.12)",
        glow: "0 0 0 3px rgba(79, 70, 229, 0.15)",
        "glow-lg": "0 0 0 4px rgba(79, 70, 229, 0.2)",
      },
      borderRadius: {
        "2xl": "1rem",
        "3xl": "1.25rem",
        "4xl": "1.5rem",
      },
      animation: {
        "fade-in": "fadeIn 400ms ease-out both",
        "fade-in-up": "fadeInUp 450ms ease-out both",
        "fade-in-down": "fadeInDown 400ms ease-out both",
        "scale-in": "scaleIn 300ms ease-out both",
        shimmer: "shimmer 1.4s linear infinite",
        "pulse-soft": "pulseSoft 2s ease-in-out infinite",
        float: "float 4s ease-in-out infinite",
      },
      transitionTimingFunction: {
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
    },
  },
  plugins: [],
};
